### ISSUE TITLE
ora2pg integration

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgtt#1]
Tested and validated that this works.  What a great extension!  In the past I used a snippet of SQL code that I found to install to simulate a GTT.  

So this gets me to thinking about **ora2pg**... Right now ora2pg does not support extraction of GTTs from oracle since PG doesn't support them.  But with this extension and if a boolean is turned on in parms to ora2pg, enable_GTT, the GTTs would be downloaded and assuming the target PG database has gtt extension created and loaded, I wonder if we could add the feature to migrate GTTs?

I haven't thought it all through yet, but whatcha think?

**Comment by darold** [comment]
Yes this is the objective of this extension to allow Ora2Pg to migrate Oracle GTT. I'm adding an issue to Ora2Pg to not forget :-) Many thanks for the tests Michael and for the confirmation that it works.
