### ISSUE TITLE
Wrong error about constraint on regular table 

### ISSUE THREAD

**Issue by ukolovda** [darold/pgtt#10]
After some actions (don't know which) I start get errors on regular tables:

```SQL
mvno_db2=> LOAD '$libdir/plugins/pgtt';
LOAD
mvno_db2=> CREATE TABLE test2(
mvno_db2(>   t1_id integer,
mvno_db2(>   FOREIGN KEY (t1_id)
mvno_db2(>   REFERENCES t1(id)
mvno_db2(>   ) ;
ERROR:  attempt to create referential integrity constraint on global temporary table
```

It occured on all tables with inlined `Foreign Key` constraint in the table scripts.
I have no GTT with this name in database.

**Comment by ukolovda** [comment]
I drop and create database with the same name before. 
May be, some counters was reset and have reused, and I got this errors? Server restart did not help.
I can send database dump, if it help.

**Comment by darold** [comment]
That's ok I was able to reproduce, last commit 1ddd633 might fix the issue.

**Comment by ukolovda** [comment]
Worked fine, thank you!
