### ISSUE TITLE
PGTT for the cloud?

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgtt#16]
Currently, this extension will not work for postgres in the cloud because of its direct ties to the underlying operating system.  

Is there a mini-version of pgtt that can be created for cloud installations like AWS that just comes with SQL stuff to load to get it to work?  I'm thinking of another file being added to this project that contains SQL stuff to manually load into a target PG server to get the functionality of pgtt, even if it is limited in some respects.

**Comment by darold** [comment]
Hi, this not possible, the pgtt extension uses several PostgreSQL hooks so it need the C code part. You should ask to AWS to support PGTT. They might have some interest as they offer some migration solution.

**Comment by MichaelDBA** [comment]
Funny that you should say that about AWS.  They do have something that tries to act like PGTT in their SCT tool.  Unfortunately, it kinda sucks.  Does not support indexes.  Thanks for the response.
