### ISSUE TITLE
2.4.0 fails to build against PG 10 and 9.6

### ISSUE THREAD

**Issue by devrimgunduz** [darold/pgtt#17]
Hi,

The latest version fails to build against v10 and 9.6 Below is the error. Can you please take a look? Thanks!

Cheers, Devrim

> + /usr/bin/make USE_PGXS=1 -j4
make[1]: Entering directory '/var/lib/pgsql/rpm10/BUILD/pgtt-2.4'
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/pgsql-10/include -Wno-uninitialized -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgtt.o pgtt.c
pgtt.c: In function 'gtt_check_command':
pgtt.c:901:10: warning: passing argument 4 of 'RangeVarGetRelidExtended' makes integer from pointer without a cast [-Wint-conversion]
          RangeVarCallbackOwnsRelation, NULL);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from pgtt.c:24:
/usr/pgsql-10/include/server/catalog/namespace.h:57:49: note: expected 'bool' {aka 'char'} but argument is of type 'void (*)(const RangeVar *, Oid,  Oid,  void *)' {aka 'void (*)(const struct RangeVar *, unsigned int,  unsigned int,  void *)'}
        LOCKMODE lockmode, bool missing_ok, bool nowait,
                                            ~~~~~^~~~~~
pgtt.c:900:12: error: too few arguments to function 'RangeVarGetRelidExtended'
    relid = RangeVarGetRelidExtended(stmt->relation, ShareLock, 0,
            ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from pgtt.c:24:
/usr/pgsql-10/include/server/catalog/namespace.h:56:12: note: declared here
 extern Oid RangeVarGetRelidExtended(const RangeVar *relation,
            ^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pgtt.o] Error 1

**Comment by darold** [comment]
Thanks for the report I will check that tomorrow.

**Comment by darold** [comment]
Port to 9.6 have been fixed with a new release published https://github.com/darold/pgtt/releases/tag/v2.5

**Comment by devrimgunduz** [comment]
Thanks!
