### ISSUE TITLE
Installation problem with clang

### ISSUE THREAD

**Issue by MichaelDBA** [darold/pgtt#2]
I'm on a new host and having problems installing pgtt.

wget https://github.com/darold/pgtt/archive/master.zip
unzip master.zip
cd pgtt-master/
export PATH=/usr/pgsql-12/bin/:$PATH
make
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/pgsql-12/include -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pgtt.bc pgtt.c
make: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make: *** [pgtt.bc] Error 127

I installed:
yum install clang.x86_64
yum install clang-devel.x86_64

But that didn't change anything.

Suggestions?

**Comment by darold** [comment]
I guess that this is because you have installed the postgresql12-llvmjit package so you might need to install the `devtoolset-7` and `llvm-toolset-7` packages.

**Comment by MichaelDBA** [comment]
Thanks, problem solved.  Perhaps  add this info....

In this case, you need access to SCLs for CentOS, so you need to install the CentOS Linux Software Collections release file. It is part of the CentOS Extras repository (x86_64 only) and can be installed with this command:
`yum install centos-release-scl`

Then install the following package which will install all the other dependency packages:
`yum install llvm-toolset-7.x86_64`
