### ISSUE TITLE
Background worker "parallel worker" was terminated by signal 11: Segmentation fault after loading PGTT

### ISSUE THREAD

**Issue by ukolovda** [darold/pgtt#21]
When I load PGTT in many sessions (for mass task scheduler), I've got the error:

`Background worker "parallel worker" (PID XXX) was terminated by signal 11: Segmentation fault`
and server process crushing.

After I disable parallel worker in PostgreSQL config:
`max_parallel_workers=0`
it works fine.

I used PostgreSQL 14 docker version with PGTT, orafce and pg_curl extensions.
Docker image on dockerhub:
`docker pull ukolovda/pg_mvno:14.0`

**Comment by MichaelDBA** [comment]
YIKES! Will be following this issue closely

**Comment by darold** [comment]
I can reproduce the issue, looking deeper.

**Comment by darold** [comment]
Commit f994733 might fix this issue.

**Comment by ukolovda** [comment]
> Commit [f994733](https://github.com/darold/pgtt/commit/f994733480185eb5ba87d0fc54ffadbcd55830a5) might fix this issue.

Thank you! Now it doesn't crush.

**Comment by YuriKulaghin** [comment]
I also got the error ```"background worker "parallel worker" (PID nnn) was terminated by signal 11: Segmentation fault"``` with PostgreSQL 13.4 and pgtt-2.6 during new database creation from many SQL and CSV files. Commit f994733 helped solve the problem, thanks!

**Comment by darold** [comment]
Release 2.7 published including the fix, closing.
