### ISSUE TITLE
Unable to install pgtt on Ubuntu

### ISSUE THREAD

**Issue by suvaytranh** [darold/pgtt#22]
After download and untar pgtt-2.6 to a directory, I moved into the untar directory then run make command line, the following error occurred.
`~/pgtt-2.6$ make 

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I/usr/include/postgresql -Wno-uninitialized -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pgtt.o pgtt.c
pgtt.c:12:10: fatal error: postgres.h: No such file or directory
   12 | #include "postgres.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: pgtt.o] Error 1`

Can anyone  help and instruct me how to install pgtt on postgres 14 in Ubuntu environment? Thanks in advance.

**Comment by darold** [comment]
Actually the current development code fix this issue but I will try to publish a new release in next hours.

**Comment by darold** [comment]
Sorry I have made a mistake when reading the git log output, actually version 2.6 supports PG14. Reading more carefully at your error message I think that the problem is that you have not installed the header files. Do the following:
```
sudo apt install postgresql-server-dev-14
```
That should fix the issue.

**Comment by darold** [comment]
Release 2.7 published, see https://github.com/darold/pgtt/releases/tag/v2.7
