### ISSUE TITLE
Global temporary table not visible in different sessions

### ISSUE THREAD

**Issue by duursma** [darold/pgtt#26]
After the creation of a global temporary table I can select from it and get an empty list.  If I repeat that select in a different session it will say the table does not exist.  If I try to re-create the table in the second session it succeeds.

As far as I know the main feature difference with the oracle global temporary table is that you only have to create it once and it can be reused in subsequential sessions.

**Comment by darold** [comment]
I don't know what you are doing exactly but perhaps the extension has not been loaded in your second session. Here is a working example:
```
contrib_regression=# LOAD 'pgtt';
LOAD
contrib_regression=# CREATE /*GLOBAL*/ TEMPORARY TABLE t_glob_temptable1 (id integer, lbl text) ON COMMIT PRESERVE ROWS;CREATE TABLE
contrib_regression=# INSERT INTO t_glob_temptable1 VALUES (1, 'One');
INSERT 0 1
contrib_regression=# SELECT * FROM t_glob_temptable1;
 id | lbl 
----+-----
  1 | One
(1 line)

contrib_regression=# \c - -
You are now connected to database "contrib_regression" as user "gilles".
contrib_regression=# LOAD 'pgtt';
LOAD
contrib_regression=# INSERT INTO t_glob_temptable1 VALUES (2, 'Two');
INSERT 0 1
contrib_regression=# SELECT * FROM t_glob_temptable1;
 id | lbl 
----+-----
  2 | Two
(1 line)
```

Note that the transaction where you have created the GTT must have been committed to be available in other sessions. Creating a GTT is a DBA task.

**Comment by duursma** [comment]
I thought I tested all combinations.  But the commit seems to do the trick.  This commit is probably done by my original test-case using ora2pg.  But that seems to miss the  'load' directive.  Thanks.
