### ISSUE TITLE
why pgtt2.9 in Postgresql14.6 can not run in parallel processes?  

### ISSUE THREAD

**Issue by jayhsiang** [darold/pgtt#30]
In multi  parallel process env,  many locks are generated. I start 50 threads simultaneously, one connection per thread, performing DML operations on the same GTT table. 
When I start java thread pool process, Some thread will be hang, as the same time , I can not access to GTT table.

**Comment by liyaojinli** [comment]
I reproduced the problem by following the steps below

1. Log into a console and perform insert into **tempTable** without committing a transaction

2. Log into another console and insert into **tempTable**. Execution will be stuck

3. If I commit a transaction from the first console, the other console is no longer stuck

Please tell me how to solve the above problems, thank you

**Comment by darold** [comment]
@liyaojinli, I'm not able to reproduce the problem with your steps even if I use UPDATE of same "rows".

@jayhsiang I will try to generate such load to see the behavior.

**Comment by darold** [comment]
@jayhsiang / @liyaojinli can you give a try to latest development code and confirm that the last fix with commit a1588a2 solves your issues?

**Comment by jayhsiang** [comment]
@darold thanks for you new commit.  The last fix with commit  a1588a2  solve  issues. this commit need release a new version as soon as pooible.

**Comment by darold** [comment]
New release [v2.10](https://github.com/darold/pgtt/releases/tag/v2.10) have been released.
