### ISSUE TITLE
Missing regcomp/regexec/regfree while compiling with Visual Studio 

### ISSUE THREAD

**Issue by lls88** [darold/pgtt#32]
Hi, 
i'm trying to compile the pgtt.c file with visual studio, but ends with unresolved external symbol for the function calls of regcomp/regexec/regfree. 

I try to write a patch for these functions using pg_regcomp/pg_regexec/pg_regfree, but the parameters are not matching. 
     
       static int regcomp(regex_t* re, char const  *string, int flags)
      {
	     auto len = strlen(string); //right??
             auto collation = LC_COLLATE;//???
	      return pg_regcomp(re, string, **len**, flags, **colation**);
      }
     static int regexec(const regex_t* restrict preg, const char* restrict string,
	      size_t nmatch, regmatch_t pmatch[restrict], int eflags)
      {
	      auto len = strlen(string); // right?
	      auto search_start = ??;
              rm_detail_t * details = ????
	      return pg_regexec(preg, string, len, **search_start, details ,**nmatch, pmatch, eflags);
      }

Do you have any idea, what values for collation in regcomp and search_start, details in regexec?

Regards,
Lanlan

**Comment by darold** [comment]
What is your PostgreSQL version ?

**Comment by lls88** [comment]
> What is your PostgreSQL version ?

13

**Comment by darold** [comment]
Can you post the exact error reported by make?

**Comment by lls88** [comment]
> Can you post the exact error reported by make?
I'm using visual studio under windows, it compiles the c file with msvc. 

Build started...
1>------ Build started: Project: gptt, Configuration: Debug x64 ------
1>pgtt.c
1>C:\Program Files\PostgreSQL\13\include\server\nodes\pg_list.h(314,11): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
1>C:\Program Files\PostgreSQL\13\include\server\libpq\pqformat.h(116,10): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Program Files\PostgreSQL\13\include\server\libpq\pqformat.h(111,15): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>C:\Work\Program\pgtt-2.10\pgtt.c(297,6): warning C4013: 'regcomp' undefined; assuming extern returning int
1>C:\Work\Program\pgtt-2.10\pgtt.c(363,2): warning C4013: 'regfree' undefined; assuming extern returning int
1>C:\Work\Program\pgtt-2.10\pgtt.c(486,26): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:\Work\Program\pgtt-2.10\pgtt.c(525,8): warning C4013: 'regexec' undefined; assuming extern returning int
1>C:\Work\Program\pgtt-2.10\pgtt.c(1120,22): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
1>C:\Work\Program\pgtt-2.10\pgtt.c(1349,31): warning C4047: 'function': 'const char *' differs in levels of indirection from 'int'
1>C:\Work\Program\pgtt-2.10\pgtt.c(1349,27): warning C4024: 'GetGttByName': different types for formal and actual parameter 1
1>C:\Work\Program\pgtt-2.10\pgtt.c(1351,4): warning C4022: 'hash_search': pointer mismatch for actual parameter 2
1>C:\Work\Program\pgtt-2.10\pgtt.c(1348,9): warning C4047: 'initializing': 'int' differs in levels of indirection from 'char *'
1>   Creating library C:\postgresql_ext_pgtt\gptt\x64\Debug\gptt.lib and object C:\Work\workspaces\GC Products\postgresql_ext_pgtt\gptt\x64\Debug\gptt.exp
1>pgtt.obj : error LNK2019: unresolved external symbol regcomp referenced in function _PG_init
1>pgtt.obj : error LNK2019: unresolved external symbol regfree referenced in function exitHook
1>pgtt.obj : error LNK2019: unresolved external symbol regexec referenced in function gtt_check_command
1>C:\postgresql_ext_pgtt\gptt\x64\Debug\gptt.dll : fatal error LNK1120: 3 unresolved externals
1>Done building project "gptt.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:01,794 ==========

I can try to build it with make. :)

**Comment by lls88** [comment]
> Can you post the exact error reported by make?

now i tried with gnu make to compile it, but it complains that there's no target...

**Comment by darold** [comment]
In commit 5a5381b I have rewritten pgtt.c to use the pg_reg* functions. Please give it a try and let me know.
Note that port to PG 16 is broken, I will try to fix that later if the fix is the right one.

**Comment by lls88** [comment]
> In commit [5a5381b](https://github.com/darold/pgtt/commit/5a5381b1f1d96b836d522ded41d342bedf3e5dcd) I have rewritten pgtt.c to use the pg_reg* functions. Please give it a try and let me know. Note that port to PG 16 is broken, I will try to fix that later if the fix is the right one.

Many thanks! It compiles under windows. 
There's only one  small difference on the elog marco using #if #else #endif. 
In windows should look like this:

#if PG_VERSION_NUM < 150000
				elog(DEBUG1, "looking for dropping table: %s", relationNameValue->val.str);
#else
				elog(DEBUG1, "looking for dropping table: %s", relationNameValue->sval);
#endif


#if PG_VERSION_NUM < 150000
					elog(DEBUG1, "looking if table %s is registered as GTT",
						relationNameValue->val.str);
					gtt_unregister_gtt_not_cached(relationNameValue->val.str);
#else
					elog(DEBUG1, "looking if table %s is registered as GTT",
						relationNameValue->sval);
					gtt_unregister_gtt_not_cached(relationNameValue->sval);
#endif

Otherwise it is perfect! ;-)

I will test the extension afterwards in postgresql.

Regards,
Lanlan

**Comment by darold** [comment]
Commit 8d6851d applies your patch.
