### ISSUE TITLE
session_preload_library support?

### ISSUE THREAD

**Issue by shane-borden** [darold/pgtt#47]
I notice that the code in the main branch appears to support `session_preload_libraries` but it is unclear whether or not the the code in the main branch is ready to deploy as the `pgtt.control` file still shows version 3.2.

Any idea when the release will occur that supports `session_preload_libraries`?

**Comment by shane-borden** [comment]
Thank you for the follow up. I will be looking for the release!

**Comment by darold** [comment]
@shane-borden version 4.0 have been just published.

**Comment by shane-borden** [comment]
Awesome!!!Shane ***@***.*** from my iPhoneOn May 30, 2024, at 8:11 PM, Gilles Darold ***@***.***> wrote:﻿
@shane-borden version 4.0 have been just published.
