### ISSUE TITLE
Not passing one of the test

### ISSUE THREAD

**Issue by fforkboat** [darold/pgtt#6]
Hi there. I am on WSL2 Ubuntu 20.04 with PG 12.6. And after installation, I found that the test named '08_plplgsql' failed. 

Test output:
![image](https://user-images.githubusercontent.com/35108699/110244405-83a0a800-7f99-11eb-9920-bb624861a087.png)

The diff result:
![image](https://user-images.githubusercontent.com/35108699/110244419-90bd9700-7f99-11eb-8dd0-2329d0e6e560.png)

**Comment by fforkboat** [comment]
BTW. It seems like the behavior is not right...

![image](https://user-images.githubusercontent.com/35108699/110245332-96b57700-7f9d-11eb-8291-141a85039ea3.png)

**Comment by darold** [comment]
I don't know what's wrong on your installation but in a similar system I can not reproduce the issue your are facing.
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

$ make installcheck
/usr/lib/postgresql/12/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/12/bin'    --inputdir=test --dbname=contrib_regression 00_init 01_oncommitdelete 02_oncommitpreserve 03_createontruncate 04_rename 05_useindex 06_createas 07_createlike 08_plplgsql 09_transaction 10_foreignkey 11_after_error
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test 00_init                      ... ok           95 ms
test 01_oncommitdelete            ... ok           85 ms
test 02_oncommitpreserve          ... ok           73 ms
test 03_createontruncate          ... ok           89 ms
test 04_rename                    ... ok          119 ms
test 05_useindex                  ... ok           97 ms
test 06_createas                  ... ok           65 ms
test 07_createlike                ... ok           93 ms
test 08_plplgsql                  ... ok           98 ms
test 09_transaction               ... ok           93 ms
test 10_foreignkey                ... ok           40 ms
test 11_after_error               ... ok           76 ms

======================
 All 12 tests passed. 
======================
```

Maybe check that you have version 2.2 of pgtt installed.

**Comment by fforkboat** [comment]
Yeah pgtt 2.2 has been installed.

I run the test again, and now everying is fine. (I have run the test several times after installation, but all of them have failed)
Don't know why it's working now... I have done nothing.

BTW, thanks for your answer and the great work of pgtt.
