### ISSUE TITLE
unrecognized node type For PG10 and PG11

### ISSUE THREAD

**Issue by smallcookie086** [darold/pgtt#7]
postgres=# \d+ test_tt
Did not find any relation named "test_tt".
postgres=# LOAD 'pgtt';
LOAD
postgres=# \d+ test_tt
                           Unlogged table "pgtt_schema.test_tt"
 Column |  Type   | Collation | Nullable | Default | Storage  | Stats target | Description 
--------+---------+-----------+----------+---------+----------+--------------+-------------
 id     | integer |           |          |         | plain    |              | 
 lbl    | text    |           |          |         | extended |              | 

postgres=# INSERT INTO test_tt VALUES (1, 'one'), (2, 'two'), (3, 'three');
ERROR:  unrecognized node type: 375
postgres=# select * from test_tt;
ERROR:  unrecognized node type: 375
postgres=# select version();
                                                 version                                                  
----------------------------------------------------------------------------------------------------------
 PostgreSQL 11.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

This is the problem I encountered during my test. Could you tell me how to solve it？
It looks like there is a problem with "PGTT provide a query string".

**Comment by smallcookie086** [comment]
Well, It is ok in 10.5 ……
Maybe there is a problem with the non-release version code. 
Thank you anyway.

**Comment by darold** [comment]
I can reproduce the problem on 11 and 10, I will fix that it should work from 9.5 to 13 the same way.

**Comment by darold** [comment]
Commit 0e13898 fix this portability problem. Thanks for the report.

**Comment by smallcookie086** [comment]
Thank you for your reply.
I have another question, why can't "pgtt.so" be preloaded? If it can, what should I do?

**Comment by darold** [comment]
This is because pgtt need to be loaded in a real session, when used through GUC session_preload_libraries it is loaded too early some information are not yet available and especially when the extension is trying to force the search_path. This is why it must be loaded using LOAD, but this can be done immediately after your application is opening a connection.
