### ISSUE TITLE
COMMENT ON TABLE or COLUMN not works for GTT

### ISSUE THREAD

**Issue by ukolovda** [darold/pgtt#9]
When I execute
`COMMENT ON TABLE G_T_TABLE IS 'Temp table for...';`
or
`COMMENT ON COLUMN G_T_TABLE.COL1 IS 'Column description';`
I'v got the error:
`a temporary table has been created and is active, can not add a comment on the GTT table in this session.`

**Comment by ukolovda** [comment]
But now I got other error.
`must be owner of table rest_postpaid_invoice_details`
It works on permanent tables, but not for GTT.

**Comment by ukolovda** [comment]
The same error on `CREATE INDEX`.
@darold , what can I do to help resolve this trouble?

**Comment by darold** [comment]
I can reproduce the comment error, just give me the create index statement to try to reproduce. I will work on this asap.

**Comment by darold** [comment]
as a workaround you can prefix the GTT table with `pgtt_schema.` it should work.

**Comment by ukolovda** [comment]
```
$ psql -U mvno_db3 -W mvno_db3;
psql (12.6)
Type "help" for help.

mvno_db3=> CREATE GLOBAL TEMPORARY TABLE GTT_WITH_INDEX2(
mvno_db3(>   REQUEST_ID numeric not null
mvno_db3(> ) ON COMMIT PRESERVE ROWS;
WARNING:  GLOBAL is deprecated in temporary table creation
LINE 1: CREATE GLOBAL TEMPORARY TABLE GTT_WITH_INDEX2(
               ^
CREATE TABLE

mvno_db3=> CREATE INDEX I_GTT_WITH_INDEX2_REQUEST_ID ON GTT_WITH_INDEX2(REQUEST_ID);
CREATE INDEX

mvno_db3=> drop TABLE GTT_WITH_INDEX2;
DROP TABLE

mvno_db3=>  LOAD '$libdir/plugins/pgtt';
LOAD

mvno_db3=> CREATE GLOBAL TEMPORARY TABLE GTT_WITH_INDEX2(
mvno_db3(>   REQUEST_ID numeric not null
mvno_db3(> ) ON COMMIT PRESERVE ROWS;
WARNING:  GLOBAL is deprecated in temporary table creation
LINE 1: CREATE GLOBAL TEMPORARY TABLE GTT_WITH_INDEX2(
               ^
CREATE TABLE

mvno_db3=> CREATE INDEX I_GTT_WITH_INDEX2_REQUEST_ID ON GTT_WITH_INDEX2(REQUEST_ID);
ERROR:  must be owner of table gtt_with_index2
```

**Comment by ukolovda** [comment]
> as a workaround for the comment you can prefix the GTT table with `pgtt_schema.` it should work.
```SQL
mvno_db3=> CREATE INDEX I_GTT_WITH_INDEX2_REQUEST_ID ON pgtt_schema.GTT_WITH_INDEX2(REQUEST_ID);
ERROR:  must be owner of table gtt_with_index2
```

**Comment by darold** [comment]
Sorry I was talking about the comment statement.  About the index I can not reproduce the problem:
```
contrib_regression=# CREATE GLOBAL TEMPORARY TABLE t1 ( a integer ) ON COMMIT PRESERVE ROWS;
WARNING:  GLOBAL is deprecated in temporary table creation
LIGNE 1 : CREATE GLOBAL TEMPORARY TABLE t1 ( a integer ) ON COMMIT PRE...
                 ^
CREATE TABLE
contrib_regression=# CREATE INDEX test_idx ON t1(a);
CREATE INDEX
contrib_regression=# DROP TABLE t1;
DROP TABLE
contrib_regression=# LOAD 'pgtt.so';
LOAD
contrib_regression=# CREATE GLOBAL TEMPORARY TABLE t1 ( a integer ) ON COMMIT PRESERVE ROWS;
WARNING:  GLOBAL is deprecated in temporary table creation
LIGNE 1 : CREATE GLOBAL TEMPORARY TABLE t1 ( a integer ) ON COMMIT PRE...
                 ^
CREATE TABLE
contrib_regression=# CREATE INDEX test_idx ON t1(a);
CREATE INDEX
contrib_regression=# DROP TABLE t1;
DROP TABLE
```

**Comment by ukolovda** [comment]
Oh, sorry.

```SQL
mvno_db3=> comment on table GTT_WITH_INDEX2 is 'c1';
ERROR:  must be owner of table gtt_with_index2
mvno_db3=> comment on table pgtt_schema.GTT_WITH_INDEX2 is 'c1';
ERROR:  must be owner of table gtt_with_index2
```

Indexes works fine before error occured first time (when I dropped table from other user).
After it begin got error about owner (the same as for comments).

**Comment by darold** [comment]
Adding comment and index on global temporary table is a maintenance task that mus be performed by a granted user and in a session where the table have not been used yet. The reason is that once the table is used (by a SELECT from or an INSERT into the global temporary table) these operation will be done on the regular temporary table created and not on the underlying template table. Generally Global Temporary Table are created once and maintained by the DBA, other users don't drop the table or add index on it. For this kind of use PostgreSQL regular temporary table is probably what you should use. 

However thanks for the feedback, I have improved the comment and create index support by pgtt in commit d48b436.
